version: '3'
volumes:
  postgres-data: {}

services:
  db:
    image: postgres:13.0-alpine
    container_name: workinmena-db
    env_file:
      - ./workinmena-api/.env.production.db
    hostname: db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  analyzer:
    build:
      context: ./workinmena-analyzer/
    image: workinmena-analyzer
    container_name: workinmena-analyzer
    ports:
      - 3001:3001
  api:
    build:
      context: ./workinmena-api/
    image: workinmena-api
    container_name: workinmena-api
    env_file:
      - ./workinmena-api/.env.production.db
    command: ./docker-entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - ./workinmena-api/puma:/app/puma
    depends_on:
      - db
      - analyzer
  app:
    build:
      context: ./workinmena-app/
    image: workinmena-app
    container_name: workinmena-app
    ports:
      - 80:80
    volumes:
      - ./workinmena-api/puma:/app/puma
    depends_on:
      - api
