version: '3'
volumes:
  postgres-data: {}

services:
  db:
    image: postgres:13.0-alpine
    container_name: workinmena-db
    env_file:
      - ./workinmena-api/.env.production.db
    hostname: db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  analyzer:
    build:
      context: ./workinmena-analyzer/
    image: workinmena-analyzer
    container_name: workinmena-analyzer
    ports:
      - 3001:3001
    environment:
      - mode=production
    volumes:
      - ./workinmena-app/nginx/certbot/conf:/etc/letsencrypt
      - ./workinmena-app/nginx/certbot/www:/var/www/certbot
  api:
    build:
      context: ./workinmena-api/
    image: workinmena-api
    container_name: workinmena-api
    env_file:
      - ./workinmena-api/.env.production.db
    command: ./docker-entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - ./workinmena-api/puma:/app/puma
      - ./workinmena-app/nginx/certbot/conf:/etc/letsencrypt
      - ./workinmena-app/nginx/certbot/www:/var/www/certbot
    depends_on:
      - db
      - analyzer
  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # command: certonly --webroot --webroot-path=/var/www/certbot --email aonemdsaleh@gmail.com --agree-tos --no-eff-email -d workinmena.tech -d www.workinmena.tech
    volumes:
      - ./workinmena-app/nginx/certbot/conf:/etc/letsencrypt
      - ./workinmena-app/nginx/certbot/www:/var/www/certbot
      - ./workinmena-app/nginx/certbot/logs:/var/log/letsencrypt
  app:
    build:
      context: ./workinmena-app/
    image: workinmena-app
    container_name: workinmena-app
    ports:
      - 80:80
      - 443:443
    # restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./workinmena-app/nginx/certbot/conf:/etc/letsencrypt
      - ./workinmena-app/nginx/certbot/www:/var/www/certbot
      - ./workinmena-api/puma:/app/puma
    depends_on:
      - api
