version: '3'
volumes:
  postgres-data: {}

services:
  db:
    image: postgres:13.0-alpine
    env_file:
      - .env.production.db
    hostname: db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api:
    build: .
    image: workinmena-api
    container_name: workinmena-api
    env_file:
      - .env.production.db
    command: ./docker-entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - ./puma:/app/puma
    depends_on:
      - db
