version: '3'
services:
  db:
    image: postgres:11.2
  api:
    build: .
    image: workinmena-api
    container_name: workinmena-api
    command: ./docker-entrypoint.sh
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
